export const InitialValues = {
  fname: "",
  lname: "",
  address: "",
  phone: "",
  email: "",
  schoolname: "",
  schoolcgpa: "",
  schoolpassyear: "",
  Degree: "",
  course: "",
  branch: "",
  degreecgpa: "",
  degreepassyear: "",
  companyname: "",
  jobtitle: "",
  jobdescription: "",
  experience: "",
};
